### ISSUE TITLE
Unable to install package paho-mqtt==1.5.0: ERROR: Cannot install paho-mqtt==1.5.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### ISSUE THREAD

**Issue by ryguy6011** [jfarmer08/ha-sengledapi#64]
Unable to install package paho-mqtt==1.5.0: ERROR: Cannot install paho-mqtt==1.5.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

After updating to core-2022.3.0. I receive this message.

**Comment by psu1989** [comment]
my working install is throwing a similar error after the latest upgrade to core-2022.3.0
Setup failed for sengledapi: Requirements for sengledapi not found: ['paho-mqtt==1.5.0'].

**Comment by Valdorama** [comment]
Seeing other users have this issue, I've decided not to upgrade to 2022.3 just yet. I did notice however that there are a bunch of forks of this repository, and one of them has a very recent commit (an hour ago) that changes the paho-mqtt version:

[https://github.com/nate-marshall/ha-sengledapi/commit/18356be6674770bdc2a1323df33c9e773240d956](url)

Is that the change that is required to fix this issue? If so can the same thing be done to this main repository?

**Comment by BeardUp** [comment]
I looked in to the change @Valdorama linked to and removing the requirement failed for me but updating paho-mqtt==1.5.0 to paho-mqtt==1.6.1 did work for me so far with minimal testing.

**Comment by Valdorama** [comment]
Thanks @BeardUp. How do you actually deploy this change? Do you just update the contents of manifest.json and then restart HA?

**Comment by BeardUp** [comment]
Yes, thats exactly what I did.

**Comment by ryguy6011** [comment]
> Thanks @BeardUp. How do you actually deploy this change? Do you just update the contents of manifest.json and then restart HA?

Where is that file, im sorry im new to this

**Comment by ryguy6011** [comment]
JK i figured it out. thanks everyone lol

**Comment by BeardUp** [comment]
> Where is that file, im sorry im new to this
/config/custom_components/sengledapi   - you can find your location of your config folder by navigating to your Configuration section in Home Assistant and then clicking on the Info tab. 

SSH in to your server and navigate to your Home Assistant config folder. Then navigate to /custom_components/sengledapi  Once you are in the sengledapi folder, you should see the manaifest.json file. Use your text editor to make the update.

**Comment by ryguy6011** [comment]
Do I just have to hard reset my instance? I still get a configuration issue when trying to restart HA through server control

**Comment by BeardUp** [comment]
> Do I just have to hard reset my instance? I still get a configuration issue when trying to restart HA through server control

I think I got that too. I am running HA in a container to I just restarted the container. Yes, try the hard restart.

**Comment by ryguy6011** [comment]
I also am new to Github... so looking at that link that shows the manifest.json. Do i completely remove the line that has the paho line in and leave the blank [] or does it need both?

**Comment by BeardUp** [comment]
> I also am new to Github... so looking at that link that shows the manifest.json. Do i completely remove the line that has the paho line in and leave the blank [] or does it need both?

No, that threw an error and I could not restart HA. I updated mine from 1.5.0 to 1.6.1 then saved and restarted.

**Comment by Valdorama** [comment]
Upgraded to 2022.3, sengled integration failed, made the change to manifest.json, restarted by HA container -> all working now.

**Comment by jfarmer08** [comment]
Hopefully this helps. I now this needs alot more help, but I have update the mqtt requirement as stated in this thread. I have not tested the release.

**Comment by 715Steve** [comment]
Changing it to paho-mqtt>=1.5.0 should keep it working if  paho-mqtt updates.

**Comment by chconil** [comment]
In case somebody sees this. Issue has been fixed in master. In HAC, redownload the "master" version.

**Comment by Grey-Lancaster** [comment]
HCAS>INTEGRATIONS>SEGLED>3 DOTS>REDOWNLOAD
scroll to the bottom of versions to find master
fixed it for me
Thanks all,
Gramps

**Comment by mattdwilson11** [comment]
So, i updated to Master and i still having this issue. Anyone else?

**Comment by jfarmer08** [comment]
https://github.com/jfarmer08/ha-sengledapi/releases/tag/v0.2.3
